### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by AngryRoleplayer** [MuxaJIbI4/libggpk#16]
Got the latest Visual Studio. Installed the net
Launching the file.
It says "i need net framework 4.6.1"
Installed it.
Still says "i need 4.6.1" ..
![image](https://user-images.githubusercontent.com/22470478/59190038-63ee0d00-8b84-11e9-819a-39cb61899d5a.png)

**Comment by AngryRoleplayer** [comment]
![image](https://user-images.githubusercontent.com/22470478/59190388-466d7300-8b85-11e9-96ed-a93249371c6d.png)
![image](https://user-images.githubusercontent.com/22470478/59190515-96e4d080-8b85-11e9-88c0-c28c91b9b8b2.png)

**Comment by Chuanhsing** [comment]
try first one options

**Comment by AngryRoleplayer** [comment]
> try first one options

tried. Still gives errors
![image](https://user-images.githubusercontent.com/22470478/59203306-facbc100-8ba6-11e9-993b-2d7a8314acb4.png)

**Comment by zaafar** [comment]
Try creating a new ‘hello world’ project on .NET Framework 4.6.1 and see if it compiles. If it doesn’t then it’s your environment issue and you have to ensure that VS-2019 have access to your .NET Framework files...


Tonight, I am going to give it a try on VS-2019. Also, I will update the definitions for the new season.

**Comment by AngryRoleplayer** [comment]
> Try creating a new ‘hello world’ project on .NET Framework 4.6.1 and see if it compiles. If it doesn’t then it’s your environment issue and you have to ensure that VS-2019 have access to your .NET Framework files...
> 
> Tonight, I am going to give it a try on VS-2019. Also, I will update the definitions for the new season.

I am not a programmer sadly, but i will try to follow your advice!

**Comment by zaafar** [comment]
Just tested the program in VS-2019 and it's compiling fine.

@Chuanhsing I would recommend to make a release ( with bins ) ( after merging my PR ) for non-programmers to access this tool without the need to compile it. Some people doesn't like this approach so I am okay if that's the case.

**Comment by zaafar** [comment]
@AngryRoleplayer feel free to use the released version ( no need to compile anything ).
https://github.com/MuxaJIbI4/libggpk/releases/tag/v1.4
