### ISSUE TITLE
PoeStrings

### ISSUE THREAD

**Issue by aianlinb** [MuxaJIbI4/libggpk#20]
Failed to read PCBangRewardMicros.dat: Error: Row ID = 0 Field Id=Unknown0, Field Type Name = ref|string,
 Message:無法讀取資料流末端之外。
 Stacktrace:    於 System.IO.__Error.EndOfFile()
   於 System.IO.BinaryReader.ReadChar()
   於 LibDat.Types.TypeFactory.<>c.<.cctor>b__12_8(BinaryReader s) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 36
   於 LibDat.Types.TypeFactory.Read[T](BinaryReader reader) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 68
   於 LibDat.Data.ValueData`1..ctor(BaseDataType type, BinaryReader reader, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\ValueData.cs: 行 28
   於 LibDat.Data.StringData..ctor(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\StringData.cs: 行 21
   於 LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 234
   於 LibDat.Data.PointerData..ctor(PointerDataType dataType, BinaryReader reader, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\PointerData.cs: 行 34
   於 LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 203
   於 LibDat.FieldData..ctor(FieldInfo fieldInfo, BinaryReader reader) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\FieldData.cs: 行 27
   於 LibDat.RecordData..ctor(RecordInfo ri, BinaryReader inStream, Int32 index) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\RecordData.cs: 行 37
Failed to read MapConnections.dat: Error: Row ID = 128 Field Id=RestrictedAreaMessage, Field Type Name = ref|string,
 Message:無法讀取資料流末端之外。
 Stacktrace:    於 System.IO.__Error.EndOfFile()
   於 System.IO.BinaryReader.ReadChar()
   於 LibDat.Types.TypeFactory.<>c.<.cctor>b__12_8(BinaryReader s) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 36
   於 LibDat.Types.TypeFactory.Read[T](BinaryReader reader) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 68
   於 LibDat.Data.ValueData`1..ctor(BaseDataType type, BinaryReader reader, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\ValueData.cs: 行 28
   於 LibDat.Data.StringData..ctor(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\StringData.cs: 行 21
   於 LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 234
   於 LibDat.Data.PointerData..ctor(PointerDataType dataType, BinaryReader reader, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\PointerData.cs: 行 34
   於 LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 203
   於 LibDat.FieldData..ctor(FieldInfo fieldInfo, BinaryReader reader) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\FieldData.cs: 行 27
   於 LibDat.RecordData..ctor(RecordInfo ri, BinaryReader inStream, Int32 index) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\RecordData.cs: 行 37
Failed to read BuffDefinitions.dat: Error: Row ID = 1393 Field Id=Unknown9, Field Type Name = ref|string,
 Message:無法讀取資料流末端之外。
 Stacktrace:    於 System.IO.__Error.EndOfFile()
   於 System.IO.BinaryReader.ReadChar()
   於 LibDat.Types.TypeFactory.<>c.<.cctor>b__12_8(BinaryReader s) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 36
   於 LibDat.Types.TypeFactory.Read[T](BinaryReader reader) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 68
   於 LibDat.Data.ValueData`1..ctor(BaseDataType type, BinaryReader reader, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\ValueData.cs: 行 28
   於 LibDat.Data.StringData..ctor(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\StringData.cs: 行 21
   於 LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 234
   於 LibDat.Data.PointerData..ctor(PointerDataType dataType, BinaryReader reader, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\PointerData.cs: 行 34
   於 LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 203
   於 LibDat.FieldData..ctor(FieldInfo fieldInfo, BinaryReader reader) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\FieldData.cs: 行 27
   於 LibDat.RecordData..ctor(RecordInfo ri, BinaryReader inStream, Int32 index) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\RecordData.cs: 行 37
Failed to read QuestStates.dat: Error: Row ID = 0 Field Id=QuestFinished_OGGFile, Field Type Name = ref|string,
 Message:Not found int(0) value at the end of the string
 Stacktrace:    於 LibDat.Types.TypeFactory.<>c.<.cctor>b__12_8(BinaryReader s) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 39
   於 LibDat.Types.TypeFactory.Read[T](BinaryReader reader) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 68
   於 LibDat.Data.ValueData`1..ctor(BaseDataType type, BinaryReader reader, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\ValueData.cs: 行 28
   於 LibDat.Data.StringData..ctor(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\StringData.cs: 行 21
   於 LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 234
   於 LibDat.Data.PointerData..ctor(PointerDataType dataType, BinaryReader reader, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Data\PointerData.cs: 行 34
   於 LibDat.Types.TypeFactory.CreateData(BaseDataType type, BinaryReader inStream, Dictionary`2 options) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\Types\TypeFactory.cs: 行 203
   於 LibDat.FieldData..ctor(FieldInfo fieldInfo, BinaryReader reader) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\FieldData.cs: 行 27
   於 LibDat.RecordData..ctor(RecordInfo ri, BinaryReader inStream, Int32 index) 於 C:\Users\tpo\Downloads\libggpk3\LibDat\RecordData.cs: 行 37

**Comment by zaafar** [comment]
Prob not a string. I am going to look at it.

**Comment by Chuanhsing** [comment]
fixed
