### ISSUE TITLE
VisualGGPK error reading Mods.dat since 2015-06-15 patch

### ISSUE THREAD

**Issue by haesken** [MuxaJIbI4/libggpk#6]
Hey I'm having some trouble since the 2015-06-15 patch. When I try to open Mods.dat with VisualGGPK I get the following error:

```
* Unable to view item, export it if you want to view it *

Details: Failed to read dat: Actual record length = 204 not equal length defined in XML: 196
Actual record length = 204 not equal length defined in XML: 196
```

It seems to be a problem with the introduction of the new mods. A fix would be appreciated, thanks.

**Comment by QuinnCone** [comment]
Modify DatDefinitions.xml and set the Mods section to be the following, and it should fix your issue above:

<record file="Mods" length="244">
			<field id="Id" type="ref|string"/>
			<field id="Unknown0" type="int"/>
			<field id="ModTypeKey" type="long"/>
			<field id="Level" type="int"/>
			<field id="Stat1 (Stats.dat Row)" type="long"/>
			<field id="Stat2 (Stats.dat Row)" type="long"/>
			<field id="Stat3 (Stats.dat Row)" type="long"/>
			<field id="Stat4 (Stats.dat Row)" type="long"/>
			<field id="Domain" type="int"/>
			<field id="Name" type="ref|string" isUser="1"/>
			<field id="GenerationType" type="int"/>
			<field id="CorrectGroup" type="ref|string"/>
			<field id="Stat1Min" type="int"/>
			<field id="Stat1Max" type="int"/>
			<field id="Stat2Min" type="int"/>
			<field id="Stat2Max" type="int"/>
			<field id="Stat3Min" type="int"/>
			<field id="Stat3Max" type="int"/>
			<field id="Stat4Min" type="int"/>
			<field id="Stat4Max" type="int"/>
			<field id="SpawnWeightTagsKeys" type="ref|list|ulong"/>
			<field id="SpawnWeightValues" type="ref|list|uint"/>
			<field id="BuffDefinitionsKey" type="long"/>
			<field id="BuffValue" type="int"/>
			<field id="TagsKeys" type="ref|list|ulong"/>
			<field id="GrantedEffectsPerLevelKey" type="long"/>
			<field id="Data1" type="ref|list|uint"/>
			<field id="Data2" type="ref|list|uint"/>
			<field id="Metadata" type="ref|string"/>
			<field id="Data3" type="ref|list|int"/>
			<field id="Data4" type="ref|list|int"/>
			<field id="Key0" type="long"/>
			<field id="Stat5Min" type="int"/>
			<field id="Stat5Max" type="int"/>
			<field id="StatsKey5" type="long"/>
			<field id="Keys0" type="long"/>
			<field id="AchievementItemsKey" type="long"/>
      <field id="GenerationWeight_TagsKeys" type="ref|list|ulong"/>
      <field id="GenerationWeight_Values" type="ref|list|int"/>
      <field id="Data5" type="ref|list|int"/>
    </record>
